### ISSUE TITLE
@pgkit/client docs page broken / unstyled

### ISSUE THREAD

**Issue by karlhorky** [mmkal/pgkit#428]
Looking at [the docs page for `@pgkit/client`](https://www.pgkit.dev/packages/client), it's looking broken / unstyled to me in multiple browsers (latest Chrome, latest Firefox, latest Safari):

![Screenshot 2024-08-25 at 13 34 13](https://github.com/user-attachments/assets/f4cad86e-3dac-4d2e-9dc4-f337b8e21962)

I don't see any failed requests in the Network tab of the DevTools.

**Comment by mmkal** [comment]
So it is. I think I've got to get off nextra v3! Thank you.

**Comment by mmkal** [comment]
downgraded to v2 while v3 is still in alpha

**Comment by karlhorky** [comment]
Nice, thanks! Looking good now.
